// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using serviceslibrary.data;

namespace serviceslibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210212020416_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Modelslibrary.Cartegory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cartegories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Modelslibrary.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Modelslibrary.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartegoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartegoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartegoryId = 1,
                            Description = "open visual studio",
                            DueDate = new DateTime(2021, 2, 12, 3, 4, 15, 937, DateTimeKind.Local).AddTicks(5454),
                            StatusId = 1,
                            Title = "Code"
                        });
                });

            modelBuilder.Entity("Modelslibrary.Tasks", b =>
                {
                    b.HasOne("Modelslibrary.Cartegory", "Cartegory")
                        .WithMany("Task")
                        .HasForeignKey("CartegoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelslibrary.Status", "Status")
                        .WithMany("Task")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartegory");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Modelslibrary.Cartegory", b =>
                {
                    b.Navigation("Task");
                });

            modelBuilder.Entity("Modelslibrary.Status", b =>
                {
                    b.Navigation("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
